### ISSUE TITLE
not detect the voice

### ISSUE THREAD

**Issue by tareqAmen** [karz0n/esp32-i2s-mic-vad#1]
hello,, 
thank you for this project
Recently i tried to run your project but it doesn't detect the voice, can you help me please

**Comment by karz0n** [comment]
Hello. Well, this project was an experiment. I just flashed and it worked as expected.

I used:
- Visual Studio + PlatformIO
- Installed ESP IDF 6.3.2 platform
- ESP32
- INMP441 mic

Here the output:
```
➜  picocom -b 115200 -r -l /dev/ttyUSB0        
picocom v3.1
...
Type [C-a] [C-h] to see available commands
Terminal ready
I (101391) ESP32 I2S Mic VAD: Voice detected
I (102401) ESP32 I2S Mic VAD: Voice detected
...
```
Check your wiring (from INMP to ESP32):
- L/R to GND
- WS to GPIO22
- SCK to GPIO26
- SD to GPIO21
- VDD to 3v3
- GND to GND

For own project I'm using other approach based on TensorFlow Lite Micro for wake work detection.

**Comment by tareqAmen** [comment]
i tried it again and it work, But (`ESP32 I2S Mic VAD: Voice detected`) is sent permanently, is this because the sensitivity of voice detection or other issues?? and can i able to change the sensitivity ?

**Comment by karz0n** [comment]
Take a look on `webrtc_vad.h` header file, the `WebRtcVad_set_mode` function can be used to set aggressiveness mode. I think it also depends on the volume of recorded sound. In my example INMP441 is used. The value of each sample is modified before passing to WebRTC. Here the mentioned modification:
```
...
   samples[sample_index] = buffer[i] >> 12;
...
```
Here you can experiment with value `11` and record the sound and check.

**Comment by karz0n** [comment]
No, I don't how to detect only human voice.
